### ISSUE TITLE
In the navbar GitHub organization link is wrong

### ISSUE THREAD

**Issue by chamodshehanka** [gcsrilanka/openhackday-2023#8]
Change the link to this https://github.com/gcsrilanka

![Screenshot 2023-10-17 at 21 02 17](https://github.com/gcsrilanka/openhackday-2023/assets/19349315/98b2d566-7528-46ee-856d-44ab1be81eea)

**Comment by marinoffDev** [comment]
hey
can you assign this to me?

**Comment by chamodshehanka** [comment]
> hey can you assign this to me?

assigned.
